change app title and add readme
redacademy/assistlist-summer-2018 pull request #15
Opened 2018-09-04 20:55 UTC by im-chang

Changed app.js location and title, added README

2018-09-04 21:15 UTC, 10thfloor requested changes
Please update your prettier config and add single-quotes, semicolons and trailing commas.

2018-09-04 21:59 UTC, 10thfloor approved these changes

2018-09-05 16:29 UTC, siddharthparmar7 requested changes
Please make the requested changes.

2018-09-05 16:29 UTC, siddharthparmar7 commented on js/App.js
> +import { Platform, StyleSheet, Text, View } from 'react-native';
Please remove Platform module import

2018-09-05 16:29 UTC, siddharthparmar7 commented on js/App.js
>  const instructions = Platform.select({
Please remove instructions as you are not using it.

2018-09-05 16:29 UTC, siddharthparmar7 commented on js/App.js
> +        <h1>Welcome to AssistList!</h1>
Are you sure, you want this as a pull request? let me know.

2018-09-05 17:22 UTC, closed without merging